name: grocery_spending_tracker_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+7
  provider: ^6.1.1
  crypto: ^3.0.3
  http: ^1.1.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  google_mlkit_text_recognition: ^0.11.0
  permission_handler: ^11.1.0
  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.19.0
  awesome_notifications: ^0.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  mockito: ^5.4.4
  test: ^1.24.3

flutter:
  uses-material-design: true
