name: grocery_spending_tracker_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+7
  provider: ^6.1.1
  crypto: ^3.0.3
  http: ^1.1.0
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  google_mlkit_text_recognition: ^0.11.0
  permission_handler: 11.0.1
  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  persistent_bottom_nav_bar: ^5.0.2
  fl_chart: ^0.65.0
  smooth_page_indicator: ^1.1.0
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  mockito: ^5.4.4
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - .env
