name: run-tests

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
      - uses: dart-lang/setup-dart@v1
      - name: Get dependencies
        run: flutter pub get
      - name: Setup repositories files
        run: dart run build_runner
      - name: Run tests
        run: flutter test